services = [
  "traefik",
  "postgres",
  "sftpgo",
  "sabredav",
  "ip-allowlist",
  "jaegertracing",
  "pgweb",
  "dozzle",
]
suffixes = ["toml", "yml", "sh", "json", "conf", "php", "py", "env"]
filenames = ["Dockerfile"]
output_dir = "rendered"
