[http.routers.pgadmin]
rule = "Host(`{{ pgadmin_domain }}`)"
service = "pgadmin"
middlewares = ["ip-allowlist"]

{% if enable_acme_resolver %}
[http.routers.pgadmin.tls]
certResolver = "leresolver"
{% endif %}

[[http.services.pgadmin.loadBalancer.servers]]
url = "http://localhost:{{ pgadmin_port }}"
